Num1 = 47
Num2 = 102
Sum= Num1 + Num2
Diff = Num2 - Num1
Product = Sum * Diff
print(Num1,"+", Num2,"=", Sum)
print(Num2,"-", Num1,"=", Diff)
print(Sum,"*", Diff,"=", Product)
print("(",Num1,"+",Num2,") * (",Num2,"-",Num1,") =",Product)